"use client"

import Footer from "@/components/Footer";
import "./globals.css";
import MainNavbar from "@/components/Navbar";
import { useEffect, useState } from "react";
import GlobalLoading from "@/components/GlobalLoading";
import { usePathname } from "next/navigation";


// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [isLoading, setIsLoading] = useState(false);
  const pathname = usePathname();

    useEffect(() => {
    setIsLoading(false);
  }, [pathname]);

  useEffect(() => {
    const handleStart = () => setIsLoading(true);
    window.addEventListener('beforeunload', handleStart);
    return () => {
      window.removeEventListener('beforeunload', handleStart);
    };
  }, []);

  return (
    <html lang="en">
      <body
      >
        {isLoading && <GlobalLoading />}
        <MainNavbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
